### PR TITLE
add streamlit Number guessing

### LINKED ISSUE #6: Create a UI for number guessing game using Streamlit
Create a nice interactive UI design using StreamLit and deploy the app if feasible.

### PR DESCRIPTION
**Pull request by stanleyedward**
Fixes #6 Create a UI for number guessing game using Streamlit

### CODE REVIEW

**Comment by aarushiksk** [comment]
Did you deploy this app? If so can you add screenshots?

**Comment by stanleyedward** [comment]
> Did you deploy this app? If so can you add screenshots?

Nope I haven't deployed it, only runs on localhost right now.
I got screenshots of it running locally

**Comment by aarushiksk** [comment]
I will appreciate it more if the app is deployed on a website. This way it becomes an end to end project ready for people to use. Do you maybe want to try deploying this? When you run your streamlit app on local host at the top right corner there appears an option to deploy the app. Do try it and let me know if it’s possible for you.

**Comment by stanleyedward** [comment]
> I will appreciate it more if the app is deployed on a website. This way it becomes an end to end project ready for people to use. Do you maybe want to try deploying this? When you run your streamlit app on local host at the top right corner there appears an option to deploy the app. Do try it and let me know if it’s possible for you.


i tried to deploy it directly from the [deploy] button on the top right,  it gave me an error that the file is not connected to an github repo repo, which is odd.
so I tried to manually deploy the app with the "through an existing repo" option.

swappy-20231004-213237

turns it'll be connected to the forked  repo and not the original one + it wont be connected to the main branch but the sub-branched created. I'm not very sure but  these might cause problems.
So might be best to try and deploy after merging to main.

i hope its not an inconvenience

**Comment by aarushiksk** [comment]
Was facing the same issue myself.... do you maybe want to try these steps? If nothing happens, do pin me again. 

To deploy a Streamlit app directly from your forked GitHub repository to Streamlit Sharing, you can follow these steps: 

### Prerequisites:

1. **Streamlit Sharing Account:** You need a Streamlit Sharing account. You can request access to the beta version at [Streamlit Sharing](https://www.streamlit.io/sharing).

### Steps to Deploy Streamlit App on Streamlit Sharing:

1. **Push Your Code to GitHub:**
   - First, make sure you have pushed your Streamlit app code to your forked GitHub repository.

2. **Create a `requirements.txt` File:**
   - Create a `requirements.txt` file in your repository root if you don't have one already. This file should list all the Python packages your app depends on.

   Example `requirements.txt`:
   ```
   streamlit
   pandas
   matplotlib
   # Add other dependencies as needed
   ```

3. **Log in to Streamlit Sharing:**
   - Log in to your Streamlit Sharing account at [Streamlit Sharing](https://www.streamlit.io/sharing).

4. **Create a New App:**
   - Create a new app on Streamlit Sharing.
   - Connect your forked GitHub repository to Streamlit Sharing during the app creation process.

5. **Configure Your App:**
   - Configure your app settings, such as the name of the app, the command to run the app (usually `streamlit run app.py` where `app.py` is the name of your main Streamlit file), and any environment variables if required.

6. **Deploy Your App:**
   - Click the "Deploy" button on Streamlit Sharing to deploy your app.
   - Streamlit Sharing will automatically fetch your code from the connected GitHub repository, install the required dependencies listed in `requirements.txt`, and deploy your app.

7. **Access Your Deployed App:**
   - Once the deployment is complete, you will be provided with a URL where your Streamlit app is live and accessible.

Remember that Streamlit Sharing is a beta service, and availability might be limited. Make sure to check the [Streamlit Sharing documentation](https://blog.streamlit.io/share-streamlit-apps-for-free-with-streamlit-sharing/) for the most up-to-date information and guidelines on deploying your apps.

**Comment by stanleyedward** [comment]
Hey I finally got it to work :D
I've hosted it at: https://noob-to-ninja-ml-guess-the-number.streamlit.app/
swappy-20231005-140515


- I was having slight issues with the `requirements.txt` file getting recognized, so I made minor adjustments to the folder name which got it to work.

**Comment by aarushiksk** [comment]
Hey! Glad you were able to host the app. I hope you learned something from this. If so, do leave a star at this repository and consider following me haha :) Happy Coding!!!!

**Pull request merged**
