### PR TITLE
Review Scrapper Added

### PR DESCRIPTION
**Pull request by Vaibhav832**
This data science project uses Python to scrape reviews from Flipkart, an Indian e-commerce platform. The project has two main goals:

1. To collect data on customer satisfaction with Flipkart products and services.

2. To use this data to identify areas where Flipkart could improve its offerings.

### CODE REVIEW

**Comment by aarushiksk** [comment]
Hi! Can you please provide a description of your project please? You can comment it down here only :)

**Comment by Vaibhav832** [comment]
Done

**Comment by aarushiksk** [comment]
Nice! Have you tried deploying this website on any cloud service?

**Comment by Vaibhav832** [comment]
Yup I deployed it on AWS during it's free trial period, but now it's not deployed anywhere.

**Comment by aarushiksk** [comment]
I added the tag in the issue you raised. You can try Vercel or Streamlit :) 
If you try so, do mention your website in the readme of the project! 
If you learned something, do drop a 🌟 and share this repo with your friends. Happy coding :)

**Pull request merged**
